# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Test Actions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
   
    - name: Build with Maven
      run: mvn install
    - name: Tests Units
      run: mvn test
    - name: Documentation
      run: mvn javadoc:javadoc
